# [deno]
# url = "https://github.com/denoland/deno"
# commit = "0d76cd50af2b21e0ac772bb5219199e32a8f312d"
# output = ["deno", "denort"]
# prefixes = ["deno::", "denort::"]

[rustdesk]
url = "https://github.com/rustdesk/rustdesk"
commit = "2ae7f00cebd3feb6acc0168f3de165bfa50a9a45"
output = ["rustdesk"]
prefixes = ["librustdesk::", "rustdesk::"]

# [tauri]
# url = "https://github.com/tauri-apps/tauri"
# commit = "94cbd40fc733e08c0bccd48149d22a0e9c2f1e5c"
# output = ["cargo-tauri", "tauri-driver", "tauri-schema-generator"]
# prefixes = ["tauri"]

[uv]
url = "https://github.com/astral-sh/uv"
commit = "aa2448ef836af43f4acd7ac7271c680174a76c76"
output = ["uv", "uvx"]
prefixes = ["uv::", "uvx::"]

[sway]
url = "https://github.com/FuelLabs/sway"
commit = "e054b396280942cb43a40bbc0b3a9b8cc30237ed"
output = [
    "forc-lsp",
    "forc-tx",
    "forc-node",
    "forc-fmt",
    "forc",
    "forc-debug",
    "forc-doc",
    "forc-submit",
    "forc-call",
    "forc-crypto",
    "forc-deploy",
    "forc-run",
    "forc-migrate",
    "forc-publish",
]

[alacritty]
url = "https://github.com/alacritty/alacritty"
commit = "3ea13aeadcfab1515367fb5e5ed5e2494b25b9a2"
output = ["alacritty"]

# [rustlings]
# url = "https://github.com/rust-lang/rustlings"
# commit = "f80fbca12e47014a314e5e931678529c28cd9fd8"
# output = ["rustlings"]

[fuel-core]
url = "https://github.com/FuelLabs/fuel-core"
commit = "cee716ff92300c07a15e9bfea60b6a0b8e823dc4"
output = [
    "fuel-core-wasm-executor",
    "fuel-core-e2e-client",
    "fuel-core-keygen",
    "fuel-core",
    "fuel-core-client",
]

# ["Magisk/native/src"]
# url = "https://github.com/topjohnwu/Magisk"
# commit = "8836a09c8cfec0718b97c9a74da3dbb608432610"
# output = []

[ripgrep]
url = "https://github.com/BurntSushi/ripgrep"
commit = "3b7fd442a6f3aa73f650e763d7cbb902c03d700e"
output = ["rg"]

[bat]
url = "https://github.com/sharkdp/bat"
commit = "185a2f343772cbb65cbf7a1d4b075b68c60e6e53"
output = ["bat"]

[meilisearch]
url = "https://github.com/meilisearch/meilisearch"
commit = "ca112a8b95ef8a40ab1d836a4565131b856aa2bc"
output = ["meilitool", "meilisearch"]

# [awesome-rust]
# url = "https://github.com/rust-unofficial/awesome-rust"
# commit = "ac32108aced77134afecc8024dcea20b69c7ff09"
# output = ["awesome-rust", "cleanup", "hacktoberfest"]

[starship]
url = "https://github.com/starship/starship"
commit = "a9261a8ed369192efff8327f075d83b8dffc2c66"
output = ["starship"]

[vaultwarden]
url = "https://github.com/dani-garcia/vaultwarden"
commit = "ad75ce281e5d0f51ef4b61e88f3f16795c6c1578"
output = ["vaultwarden"]

[typst]
url = "https://github.com/typst/typst"
commit = "87cb8f5094b9ea45893344143ca069a521f9ba47"
output = ["typst"]

# ["codex/codex-rs"]
# url = "https://github.com/openai/codex"
# commit = "029f39b9da894d27dcde81b8636ef89d8b652a9f"
# output = ["codex"]

[fuels-rs]
url = "https://github.com/FuelLabs/fuels-rs"
commit = "aed2d97bdb8ec3177596020c8e2795d62e3ff433"
output = ["change-log", "check-docs", "fuel-core-version", "versions-replacer"]

[ruff]
url = "https://github.com/astral-sh/ruff"
commit = "96660d93ca29869ae58ce423011ffa56da9a70d2"
output = ["ruff", "ruff_python_formatter"]

[helix]
url = "https://github.com/helix-editor/helix"
commit = "4f985832bff54cbe12b4e42e51ba420b091a11f0"
output = ["hx"]

[fd]
url = "https://github.com/sharkdp/fd"
commit = "b7fe2ce91b522f7bc1fdf7d86e1d52ac4a99fd69"
output = ["fd"]

[lapce]
url = "https://github.com/lapce/lapce"
commit = "8bfcc8456dd130349972432036c12d681b113068"
output = ["lapce", "lapce-proxy"]

[nushell]
url = "https://github.com/nushell/nushell"
commit = "680a2fa2aaccb0b265d971a9dcec73c3a77ee50a"
output = ["nu"]

# [polars]
# url = "https://github.com/pola-rs/polars"
# commit = "3447c6ced8cbb757862e565090d99a182dc2b8f9"
# output = ["polars", "polars-cli"]

[swc]
url = "https://github.com/swc-project/swc"
commit = "dd79147cf74384db83d5b1fa47da356a1e8bb2c4"
output = ["swc"]

# [tabby]
# url = "https://github.com/TabbyML/tabby"
# commit = "502b9c036c953e8f75bb67c77f9ed80ff9d22565"
# output = ["tabby-index-cli", "tabby"]

# [comprehensive-rust]
# url = "https://github.com/google/comprehensive-rust"
# commit = "0a734e9f0249c6525f95f05fba298b3caf76f6af"

# [yew]
# url = "https://github.com/yewstack/yew"
# commit = "85050f50fb4d211f5a96a814e175467ca87681b3"

# [servo]
# url = "https://github.com/servo/servo"
# commit = "4ea363277eecc8f24326d8a906cf44c2c06baa8c"
# output = ["servo"]

[fish-shell]
url = "https://github.com/fish-shell/fish-shell"
commit = "92d96466319c1385195734ab5e45b665d5283268"
output = ["fish", "fish_indent", "fish_key_reader"]

[linera-protocol]
url = "https://github.com/linera-io/linera-protocol"
commit = "892fff389ded63e2c45cd4dce3f09e858c59713b"
output = ["linera"]

[sniffnet]
url = "https://github.com/GyulyVGC/sniffnet"
commit = "50c4af5bd1a23a647046a0212d7232841a5977ce"
output = ["sniffnet"]

[influxdb]
url = "https://github.com/influxdata/influxdb"
commit = "c205fefa1764e5ebabe20057179c7af1425feac1"
output = ["influxdb3"]

# [dioxus]
# url = "https://github.com/DioxusLabs/dioxus"
# commit = "10912f475069e0c4e1dbbedb32f4ee16201d4c81"
# output = ["dx"]

[firecracker]
url = "https://github.com/firecracker-microvm/firecracker"
commit = "6d6c80d58de954027c890a762b8dcd180bb760d8"
output = ["firecracker"]

[zoxide]
url = "https://github.com/ajeetdsouza/zoxide"
commit = "6324b4e347a45ba7e07ec2584d11e133fad3bd84"
output = ["zoxide"]

[surrealdb]
url = "https://github.com/surrealdb/surrealdb"
commit = "dc273e4e961eacee9dc6d7b0c010f92280200534"
output = ["surreal"]

# ["tokio"]
# url = "https://github.com/tokio-rs/tokio"
# commit = "b157f5da76a50063f831112f8ca7ccc787120f50"
# output = [
#     "libtokio.o",
#     "libtokio_util.o",
#     "libtokio_test.o",
#     "libtokio_stream.o",
#     "libtokio_macros.so",
# ]

[turborepo]
url = "https://github.com/vercel/turborepo"
commit = "ddbf2bbb05366ff6793b5087d81c7b3a549450bc"
output = ["turbo", "turbo-trace", "turborepo-lsp"]

# [yazi]
# url = "https://github.com/sxyazi/yazi"
# commit = "879ed4999694c84d62ba85979e5031d58b85f85d"
# output = ["ya", "yazi"]

[just]
url = "https://github.com/casey/just"
commit = "1cd0ab309e62b8e8633dc5374d490a48651895fd"
output = ["just"]

# [iced]
# url = "https://github.com/iced-rs/iced"
# commit = "0a34496c793fd87c235e764317351a0aacd4f6d1"
# output = ["libiced.o"]

[coreutils]
url = "https://github.com/uutils/coreutils.git"
commit = "7d2fc68889edf2452e304be0a6cab751c72d091d"
output = [
    "df",
    "mv",
    "kill",
    "touch",
    "base64",
    "unlink",
    "vdir",
    "rmdir",
    "nice",
    "ln",
    "install",
    "split",
    "printenv",
    "factor",
    "printf",
    "groups",
    "uname",
    "expr",
    "false",
    "pwd",
    "base32",
    "fold",
    "uniq",
    "fmt",
    "yes",
    "cat",
    "nohup",
    "uptime",
    "true",
    "chcon",
    "mkdir",
    "echo",
    "ls",
    "who",
    "pinky",
    "comm",
    "readlink",
    "nproc",
    "csplit",
    "sync",
    "du",
    "tail",
    "numfmt",
    "dirname",
    "cksum",
    "hostid",
    "basename",
    "users",
    "chroot",
    "runcon",
    "stty",
    "sort",
    "unexpand",
    "wc",
    "shred",
    "test",
    "dircolors",
    "tr",
    "tac",
    "tsort",
    "chmod",
    "stat",
    "mktemp",
    "cp",
    "seq",
    "hashsum",
    "cut",
    "paste",
    "ptx",
    "shuf",
    "sum",
    "stdbuf",
    "id",
    "timeout",
    "tee",
    "realpath",
    "od",
    "join",
    "pathchk",
    "mknod",
    "mkfifo",
    "link",
    "head",
    "date",
    "rm",
    "more",
    "hostname",
    "truncate",
    "chown",
    "dd",
    "nl",
    "pr",
    "dir",
    "sleep",
    "basenc",
    "expand",
    "env",
    "chgrp",
    "tty",
    "whoami",
    "logname",
    "arch",
]

# [metal-crusher]
# url = "https://github.com/relativemodder/metal-crusher"
# commit = "58a351b55a5ccb9e4b92fbb45f377a5d68cb0ff2"
# output = ["metal-crusher"]

# [Auto-Color-Study]
# url = "https://github.com/KeiranY/Auto-Color-Study"
# commit = "1900f117c9e379b91fe05d38ec119512d667797f"
# output = ["binary"]

# [FakeCrypt]
# url = "https://github.com/Neyrian/FakeCrypt"
# commit = "cc4e6b160cad4a69f465fefedfc8d7b0e48f9616"
# output = ["FakeCrypt"]

# [flea]
# url = "https://github.com/rozensoftware/flea"
# commit = "f34024009c30eebbc2fb9097983a180f34b1d4e6"
# output = ["flea"]

# [spyware]
# url = "https://github.com/talbor49/spyware"
# commit = "e3b299f4ba53f69630954a04737dc5983aecd593"
# output = ["spyware"]

# ["evilkit/server"]
# url = "https://github.com/krishpranav/evilkit"
# commit = "1c1a98749bfcaaa61fdba3dcf34a2bd65e5efb8f"
# output = ["server"]

# ["evilkit/client"]
# url = "https://github.com/krishpranav/evilkit"
# commit = "1c1a98749bfcaaa61fdba3dcf34a2bd65e5efb8f"
# output = ["client"]

# [backdoor-automater]
# url = "https://github.com/darvoiteau/backdoor-automater"
# commit = "e72a01e31b9b6c3c62f2f878fbc3ea2ed86ebee8"
# output = ["backdoorautomater"]

# [harry]
# url = "https://github.com/lucascherzer/harry"
# commit = "ae548aad056b641295736c17496dc571e1245bec"
# output = ["harry"]
