[deno]
url = "https://github.com/denoland/deno"
commit = "589d66f79c2651c47c6cb6b45bb5a01d7d1b61a7"
output = ["deno", "denort"]
prefixes = ["deno::", "denort::"]

[rustdesk]
url = "https://github.com/rustdesk/rustdesk"
commit = "fa1ed2bc0ccba63f2fe464d3e1ac0276f78e882d"
output = ["rustdesk"]
prefixes = ["librustdesk::", "rustdesk::"]

# [tauri]
# url = "https://github.com/tauri-apps/tauri"
# commit = "94cbd40fc733e08c0bccd48149d22a0e9c2f1e5c"
# output = ["cargo-tauri", "tauri-driver", "tauri-schema-generator"]
# prefixes = ["tauri"]

[uv]
url = "https://github.com/astral-sh/uv"
commit = "d483b02e61892a2465fa8fd1cc1bc130e6ebbed9"
output = ["uv", "uvx"]
prefixes = ["uv::", "uvx::"]

[sway]
url = "https://github.com/FuelLabs/sway"
commit = "4927805e4b5d3fc986f27118775a2b9e3a2e0c71"
output = [
    "forc-lsp",
    "forc-tx",
    "forc-node",
    "forc-fmt",
    "forc",
    "forc-mcp",
    "forc-debug",
    "forc-doc",
    "forc-submit",
    "forc-call",
    "forc-crypto",
    "forc-deploy",
    "forc-run",
    "forc-migrate",
    "forc-publish",
]

[alacritty]
url = "https://github.com/alacritty/alacritty"
commit = "a2334ff494a26a38f66685d0f950a9b589ac84a9"
output = ["alacritty"]

# [rustlings]
# url = "https://github.com/rust-lang/rustlings"
# commit = "f80fbca12e47014a314e5e931678529c28cd9fd8"
# output = ["rustlings"]

[fuel-core]
url = "https://github.com/FuelLabs/fuel-core"
commit = "f60a0bcf96ef7c392ddb9fb7b8c4a2652db72ea3"
output = [
    "fuel-core-wasm-executor",
    "fuel-core-e2e-client",
    "fuel-core-keygen",
    "fuel-core",
    "fuel-core-client",
]

# ["Magisk/native/src"]
# url = "https://github.com/topjohnwu/Magisk"
# commit = "8836a09c8cfec0718b97c9a74da3dbb608432610"
# output = []

[ripgrep]
url = "https://github.com/BurntSushi/ripgrep"
commit = "9802945e6342ec284633924cb7d8d3ce67204995"
output = ["rg"]

[bat]
url = "https://github.com/sharkdp/bat"
commit = "2c87b9480fd98ae8a10dd07ca377031627d229ef"
output = ["bat"]

[meilisearch]
url = "https://github.com/meilisearch/meilisearch"
commit = "c29bdcae23ee3c0488a7ef02b66c845686de4372"
output = ["meilitool", "meilisearch"]

# [awesome-rust]
# url = "https://github.com/rust-unofficial/awesome-rust"
# commit = "ac32108aced77134afecc8024dcea20b69c7ff09"
# output = ["awesome-rust", "cleanup", "hacktoberfest"]

[starship]
url = "https://github.com/starship/starship"
commit = "f7d583821a01d2429cef1f243228aa04055f4760"
output = ["starship"]

[vaultwarden]
url = "https://github.com/dani-garcia/vaultwarden"
commit = "a2ad1dc7c3d28834749d4b14206838d795236c27"
output = ["vaultwarden"]

[typst]
url = "https://github.com/typst/typst"
commit = "563c8d3659e80eff6ffbea5a5a4c75115cf733da"
output = ["typst"]

# ["codex/codex-rs"]
# url = "https://github.com/openai/codex"
# commit = "029f39b9da894d27dcde81b8636ef89d8b652a9f"
# output = ["codex"]

[fuels-rs]
url = "https://github.com/FuelLabs/fuels-rs"
commit = "48f3c437394207ce8c37342ad2ce6bb6cc8076ba"
output = [
    "change-log",
    "check-docs",
    "fuel-core-version",
    "versions-replacer",
    # "libfuels_accounts.o",
    # "libfuels_code_gen.o",
    # "libfuels_core.o",
    # "libfuels_macros.so",
    # "libfuels_programs.o",
    # "libfuels_test_helpers.o",
    # "libfuels.o",
]

[ruff]
url = "https://github.com/astral-sh/ruff"
commit = "caf48f4bfc54bb587342bf794a4f5167d855f529"
output = ["ruff", "ruff_python_formatter"]

# [bevy]
# url = "https://github.com/bevyengine/bevy"
# commit = "bb26c6eacc80964d09a70c073ef16cae605b852f"
# output = [
#     "libbevy_a11y.rlib",
#     "libbevy_animation.rlib",
#     "libbevy_anti_alias.rlib",
#     "libbevy_app.rlib",
#     "libbevy_asset.rlib",
#     "libbevy_audio.rlib",
#     "libbevy_camera.rlib",
#     "libbevy_color.rlib",
#     "libbevy_core_pipeline.rlib",
#     "libbevy_dev_tools.rlib",
#     "libbevy_diagnostic.rlib",
#     "libbevy_ecs.rlib",
#     "libbevy_gilrs.rlib",
#     "libbevy_gizmos.rlib",
#     "libbevy_gltf.rlib",
#     "libbevy_image.rlib",
#     "libbevy_input.rlib",
#     "libbevy_light.rlib",
#     "libbevy_log.rlib",
#     "libbevy_math.rlib",
#     "libbevy_mesh.rlib",
#     "libbevy_pbr.rlib",
#     "libbevy_picking.rlib",
#     "libbevy_post_process.rlib",
#     "libbevy_ptr.rlib",
#     "libbevy_reflect.rlib",
#     "libbevy_remote.rlib",
#     "libbevy_render.rlib",
#     "libbevy.rlib",
#     "libbevy_scene.rlib",
#     "libbevy_shader.rlib",
#     "libbevy_sprite_render.rlib",
#     "libbevy_sprite.rlib",
#     "libbevy_state.rlib",
#     "libbevy_tasks.rlib",
#     "libbevy_text.rlib",
#     "libbevy_time.rlib",
#     "libbevy_transform.rlib",
#     "libbevy_ui_render.rlib",
#     "libbevy_ui.rlib",
#     "libbevy_utils.rlib",
#     "libbevy_window.rlib",
#     "libbevy_winit.rlib",
# ]

[helix]
url = "https://github.com/helix-editor/helix"
commit = "bfcbef10c513108c7b43317569416c2eefc4ed44"
output = ["hx"]

[fd]
url = "https://github.com/sharkdp/fd"
commit = "47cedbb44e35cb425c3c0772f77a245252df63b2"
output = ["fd"]

[lapce]
url = "https://github.com/lapce/lapce"
commit = "9cdbcf6bdf440bc6db7c3f39f76fcf0cab6262ea"
output = ["lapce", "lapce-proxy"]

[nushell]
url = "https://github.com/nushell/nushell"
commit = "7e8b09be4d8b9d7da298230a12a3dc493232c315"
output = ["nu"]

# [polars]
# url = "https://github.com/pola-rs/polars"
# commit = "718d5e5f1f23aed8c5194347388524014aad5a8c"
# output = ["polars", "polars-cli"]

[swc]
url = "https://github.com/swc-project/swc"
commit = "dd79147cf74384db83d5b1fa47da356a1e8bb2c4"
output = ["swc"]

[tabby]
url = "https://github.com/TabbyML/tabby"
commit = "01f8bb72de75221ebaa18247a6a727f494421d05"
output = ["tabby-index-cli", "tabby"]

# [comprehensive-rust]
# url = "https://github.com/google/comprehensive-rust"
# commit = "0a734e9f0249c6525f95f05fba298b3caf76f6af"
# output = [
#     "allocator-example",
#     "client",
#     "collatz",
#     "course-content",
#     "course-schedule",
#     "demo",
#     "dining-philosophers",
#     "elevator",
#     "fizzbuzz",
#     "hashset",
#     "link-checker",
#     "listdir",
#     "methods-and-traits",
#     "modules",
#     "references",
#     "server",
#     "transpose",
#     "zerocopy-example",
#     "libandroid_testing.o",
#     "libbinary_tree.o",
#     "libborrowing.o",
#     "libeval.o",
#     "libgenerics.o",
#     "libluhn.o",
#     "liboffset_differences.o",
#     "libparser.o",
#     "libprotobuf.o",
#     "libstd_traits.o",
# ]

# [yew]
# url = "https://github.com/yewstack/yew"
# commit = "85050f50fb4d211f5a96a814e175467ca87681b3"
# output = [
#     "libyew_agent_macro.so",
#     "libyew_agent.o",
#     "libyew_macro.so",
#     "libyew_router_macro.so",
#     "libyew_router.o",
#     "libyew.o",
# ]

# [servo]
# url = "https://github.com/servo/servo"
# commit = "4ea363277eecc8f24326d8a906cf44c2c06baa8c"
# output = ["servo"]

[fish-shell]
url = "https://github.com/fish-shell/fish-shell"
commit = "db6a7d26cd15448dbde8ad3b95c9841812548648"
output = ["fish", "fish_indent", "fish_key_reader"]

[linera-protocol]
url = "https://github.com/linera-io/linera-protocol"
commit = "1a2d670ac994a74940480c063894ac6d41fb8380"
output = [
    "linera",
    "linera-server",
    "linera-storage-server",
    "linera-proxy",
    "linera-indexer",
    "linera-indexer-grpc",
    "linera-benchmark",
    "linera-exporter",
    "linera-summary",
    "linera-schema-export",
]

[sniffnet]
url = "https://github.com/GyulyVGC/sniffnet"
commit = "b61f014f6c780913c7426945a11f382afb0e3f63"
output = ["sniffnet"]

[influxdb]
url = "https://github.com/influxdata/influxdb"
commit = "dfe5bf14ae34e73a9e54b1a0ae816103071a1b10"
output = ["influxdb3"]

# [dioxus]
# url = "https://github.com/DioxusLabs/dioxus"
# commit = "10912f475069e0c4e1dbbedb32f4ee16201d4c81"
# output = ["dx"]

["firecracker"]
url = "https://github.com/firecracker-microvm/firecracker"
commit = "a7356c1780f06bff4def2eaa5f20af996d351666"
output = ["firecracker"]

[zoxide]
url = "https://github.com/ajeetdsouza/zoxide"
commit = "6ac39b7f414818e9f66da5c2e34fde326897af1c"
output = ["zoxide"]

["surrealdb"]
url = "https://github.com/surrealdb/surrealdb"
commit = "2c83cd9ce078dee32eaee192c063cdb6e0daaa69"
output = ["surreal"]

# ["tokio"]
# url = "https://github.com/tokio-rs/tokio"
# commit = "b157f5da76a50063f831112f8ca7ccc787120f50"
# output = [
#     "libtokio.o",
#     "libtokio_util.o",
#     "libtokio_test.o",
#     "libtokio_stream.o",
#     "libtokio_macros.so",
# ]

["turborepo"]
url = "https://github.com/vercel/turborepo"
commit = "5186836189f8b4eb00d57769d55af44fa518a78b"
output = ["turbo", "turbo-trace", "turborepo-lsp"]

# [yazi]
# url = "https://github.com/sxyazi/yazi"
# commit = "879ed4999694c84d62ba85979e5031d58b85f85d"
# output = ["ya", "yazi"]

[just]
url = "https://github.com/casey/just"
commit = "b7e7c46495b34e9407982ffbbb25eb2808ec40b7"
output = ["just"]

# [iced]
# url = "https://github.com/iced-rs/iced"
# commit = "0a34496c793fd87c235e764317351a0aacd4f6d1"
# output = ["libiced.o"]

[coreutils]
url = "https://github.com/uutils/coreutils.git"
commit = "0c53409857ffc153c996af744d3b80089bd4898b"
output = [
    "df",
    "mv",
    "kill",
    "touch",
    "base64",
    "unlink",
    "vdir",
    "rmdir",
    "nice",
    "ln",
    "install",
    "split",
    "printenv",
    "factor",
    "printf",
    "groups",
    "uname",
    "expr",
    "false",
    "pwd",
    "base32",
    "fold",
    "uniq",
    "fmt",
    "yes",
    "cat",
    "nohup",
    "uptime",
    "true",
    "chcon",
    "mkdir",
    "echo",
    "ls",
    "who",
    "pinky",
    "comm",
    "readlink",
    "nproc",
    "csplit",
    "sync",
    "du",
    "tail",
    "numfmt",
    "dirname",
    "cksum",
    "hostid",
    "basename",
    "users",
    "chroot",
    "runcon",
    "stty",
    "sort",
    "unexpand",
    "wc",
    "shred",
    "test",
    "dircolors",
    "tr",
    "tac",
    "tsort",
    "chmod",
    "stat",
    "mktemp",
    "cp",
    "seq",
    "hashsum",
    "cut",
    "paste",
    "ptx",
    "shuf",
    "sum",
    "stdbuf",
    "id",
    "timeout",
    "tee",
    "realpath",
    "od",
    "join",
    "pathchk",
    "mknod",
    "mkfifo",
    "link",
    "head",
    "date",
    "rm",
    "more",
    "hostname",
    "truncate",
    "chown",
    "dd",
    "nl",
    "pr",
    "dir",
    "sleep",
    "basenc",
    "expand",
    "env",
    "chgrp",
    "tty",
    "whoami",
    "logname",
    "arch",
]
