[rustdesk]
url = "https://github.com/rustdesk/rustdesk"
commit = "105a7741358efad9e7718bd0fc2a435e3c721dbe"
output = ["rustdesk"]
prefixes = ["librustdesk::", "rustdesk::"]

[fselect]
url = "https://github.com/jhspetersson/fselect.git"
commit = "400440b2ba1dde9a01f3bc04370f535b18fd79d7"
output = ["fselect"]

# [uv]
# url = "https://github.com/astral-sh/uv"
# commit = "aa2448ef836af43f4acd7ac7271c680174a76c76"
# output = ["uv", "uvx"]
# prefixes = ["uv::", "uvx::"]

[sway]
url = "https://github.com/FuelLabs/sway"
commit = "7245883f09ae271bbfd77bef1656eb0c0a86e2cb"
output = [
    "forc-lsp",
    "forc-tx",
    "forc-fmt",
    "forc",
    "forc-doc",
    "forc-submit",
    "forc-deploy",
    "forc-run",
]

[alacritty]
url = "https://github.com/alacritty/alacritty"
commit = "9fcdb059bf772303e66607ccbf6f1fd6183743e9"
output = ["alacritty"]

[fuel-core]
url = "https://github.com/FuelLabs/fuel-core"
commit = "caf5397592bf3c8a7a8b98e89f7421c68ba80119"
output = [
    "fuel-core-e2e-client",
    "fuel-core-keygen",
    "fuel-core",
    "fuel-core-client",
]

[ripgrep]
url = "https://github.com/BurntSushi/ripgrep"
commit = "a7f1276021df2217dead1481b2c2b38595ed8fb3"
output = ["rg"]

[bat]
url = "https://github.com/sharkdp/bat"
commit = "7f884fa582487c3a0d8b71eaeb2c60d7e257889e"
output = ["bat"]

[meilisearch]
url = "https://github.com/meilisearch/meilisearch"
commit = "6d4981ec250fd9e09389681022a4c96ee5497215"
output = ["meilisearch"]

[starship]
url = "https://github.com/starship/starship"
commit = "52ecc411eb9074c0d4066dcbd4b732bf97e79d71"
output = ["starship"]

# [vaultwarden]
# url = "https://github.com/dani-garcia/vaultwarden"
# commit = "e7f083dee9743bfe4937f5c8149fa9d8383edb96"
# output = ["vaultwarden"]

[typst]
url = "https://github.com/typst/typst"
commit = "47a131dfbb9cf3c0adad6e0d9d669f750fbda658"
output = ["typst"]

# [fuels-rs]
# url = "https://github.com/FuelLabs/fuels-rs"
# commit = "6de98cf0550b9de9af00ddf108121a921b10d116"
# output = ["change-log", "check-docs", "fuel-core-version", "versions-replacer"]

# [ruff]
# url = "https://github.com/astral-sh/ruff"
# commit = "e0a507e48ebad7bc400f76290535673efece9229"
# output = ["ruff", "ruff_python_formatter"]

# [helix]
# url = "https://github.com/helix-editor/helix"
# commit = "2c5288dafb88ae2a12d3589b79a525932f48b6b3"
# output = ["hx"]

[fd]
url = "https://github.com/sharkdp/fd"
commit = "3ae04546eafe6d38ed8bc0d967d8f2dc38892579"
output = ["fd"]

# [lapce]
# url = "https://github.com/lapce/lapce"
# commit = "6c85e94e1d21ad2dfc42b9756f2806b5e67d6160"
# output = ["lapce", "lapce-proxy"]

[nushell]
url = "https://github.com/nushell/nushell"
commit = "a0dafcb0f89eb6161ac98fbf388040744f0a5947"
output = ["nu"]

# [swc]
# url = "https://github.com/swc-project/swc"
# commit = "4efefb0f4ef4fcbc50b32dd7b9e7b21509ab7309"
# output = ["swc"]

# [fish-shell]
# url = "https://github.com/fish-shell/fish-shell"
# commit = "c7b43b3abfb24af324100667932b168f0ef566e3"
# output = ["fish", "fish_indent", "fish_key_reader"]

[linera-protocol]
url = "https://github.com/linera-io/linera-protocol"
commit = "f9d5e47d4fe4c319b43603d6d76e4db34f31bb17"
output = ["linera"]

[sniffnet]
url = "https://github.com/GyulyVGC/sniffnet"
commit = "30254f16308417e6926e3a0a8f994dccab2a3e5a"
output = ["sniffnet"]

[influxdb]
url = "https://github.com/influxdata/influxdb"
commit = "b57a53eff40112c05fc94f48f5fc7321cd117d3d"
output = ["influxdb_iox"]

[firecracker]
url = "https://github.com/firecracker-microvm/firecracker"
commit = "5a6f28dea0fcb5c1cc61e1cb5a5cf4414eb08778"
output = ["firecracker"]

[zoxide]
url = "https://github.com/ajeetdsouza/zoxide"
commit = "5f8974fc5cf7fc26b2a175ea8e7d5ce6054f59ae"
output = ["zoxide"]

[surrealdb]
url = "https://github.com/surrealdb/surrealdb"
commit = "b4adbe9962565e777ea7eedaea8c214e0b6c4967"
output = ["surreal"]

# [turborepo]
# url = "https://github.com/vercel/turborepo"
# commit = "17fa0b177f3b52b58437651dac270f8973e67a73"
# output = ["turbo", "turbo-trace", "turborepo-lsp"]

[just]
url = "https://github.com/casey/just"
commit = "f04de756091028dd8fe31773e5f65e16d8f177ed"
output = ["just"]

[coreutils]
url = "https://github.com/uutils/coreutils.git"
commit = "b787a2ab9ac2b41c07ee92f75b7be78ec03509f9"
output = [
    "df",
    "mv",
    "kill",
    "touch",
    "base64",
    "unlink",
    "vdir",
    "rmdir",
    "nice",
    "ln",
    "install",
    "split",
    "printenv",
    "factor",
    "printf",
    "groups",
    "uname",
    "expr",
    "false",
    "pwd",
    "base32",
    "fold",
    "uniq",
    "fmt",
    "yes",
    "cat",
    "nohup",
    "uptime",
    "true",
    "chcon",
    "mkdir",
    "echo",
    "ls",
    "who",
    "pinky",
    "comm",
    "readlink",
    "nproc",
    "csplit",
    "sync",
    "du",
    "tail",
    "numfmt",
    "dirname",
    "cksum",
    "hostid",
    "basename",
    "users",
    "chroot",
    "runcon",
    "stty",
    "sort",
    "unexpand",
    "wc",
    "shred",
    "test",
    "dircolors",
    "tr",
    "tac",
    "tsort",
    "chmod",
    "stat",
    "mktemp",
    "cp",
    "seq",
    "hashsum",
    "cut",
    "paste",
    "ptx",
    "shuf",
    "sum",
    "stdbuf",
    "id",
    "timeout",
    "tee",
    "realpath",
    "od",
    "join",
    "pathchk",
    "mknod",
    "mkfifo",
    "link",
    "head",
    "date",
    "rm",
    "more",
    "hostname",
    "truncate",
    "chown",
    "dd",
    "nl",
    "pr",
    "dir",
    "sleep",
    "basenc",
    "expand",
    "env",
    "chgrp",
    "tty",
    "whoami",
    "logname",
    "arch",
]
