["rust"]
full_name = "rust-lang/rust"
url = "https://github.com/rust-lang/rust"
commit = "f437c86ef829e43c6aa27641f53040a999a092af"
loc = 2549662
stars = 106890

["deno"]
full_name = "denoland/deno"
url = "https://github.com/denoland/deno"
commit = "1573279c125ebaafcc34d09578ccc0b0c398a0ef"
loc = 288771
stars = 104578

["rustdesk"]
full_name = "rustdesk/rustdesk"
url = "https://github.com/rustdesk/rustdesk"
commit = "8d715348391497b894104d2c792d04204efc1fd5"
loc = 108009
stars = 99210

["tauri"]
full_name = "tauri-apps/tauri"
url = "https://github.com/tauri-apps/tauri"
commit = "2e089f6acb854e4d7f8eafb9b2f8242b1c9fa491"
loc = 70995
stars = 97058

["union"]
full_name = "unionlabs/union"
url = "https://github.com/unionlabs/union"
commit = "18754b896ad80a9ff2c4f45e01fea5d550080f45"
loc = 408549
stars = 74630

["uv"]
full_name = "astral-sh/uv"
url = "https://github.com/astral-sh/uv"
commit = "241ad88051bd7f164e050dcd742de44db9a2abf2"
loc = 333830
stars = 68984

["zed"]
full_name = "zed-industries/zed"
url = "https://github.com/zed-industries/zed"
commit = "6707ff3b5071893aecd459851800efe197879bf6"
loc = 798546
stars = 66625

["sway"]
full_name = "FuelLabs/sway"
url = "https://github.com/FuelLabs/sway"
commit = "8e44f537752f0b1b6ded6182a94e7aaafd49610f"
loc = 204586
stars = 62139

["alacritty"]
full_name = "alacritty/alacritty"
url = "https://github.com/alacritty/alacritty"
commit = "a2334ff494a26a38f66685d0f950a9b589ac84a9"
loc = 24897
stars = 60530

["rustlings"]
full_name = "rust-lang/rustlings"
url = "https://github.com/rust-lang/rustlings"
commit = "f80fbca12e47014a314e5e931678529c28cd9fd8"
loc = 8647
stars = 60154

["fuel-core"]
full_name = "FuelLabs/fuel-core"
url = "https://github.com/FuelLabs/fuel-core"
commit = "f60a0bcf96ef7c392ddb9fb7b8c4a2652db72ea3"
loc = 144181
stars = 57517

["Magisk"]
full_name = "topjohnwu/Magisk"
url = "https://github.com/topjohnwu/Magisk"
commit = "bcc6296d9495af41c3af6892a1259a7e1d442aa8"
loc = 12861
stars = 56194

["ripgrep"]
full_name = "BurntSushi/ripgrep"
url = "https://github.com/BurntSushi/ripgrep"
commit = "9802945e6342ec284633924cb7d8d3ce67204995"
loc = 37640
stars = 55820

["bat"]
full_name = "sharkdp/bat"
url = "https://github.com/sharkdp/bat"
commit = "6ece3063ab6a2d202e05577ee4995b0b551dbdbf"
loc = 12333
stars = 54729

["ChatGPT"]
full_name = "lencx/ChatGPT"
url = "https://github.com/lencx/ChatGPT"
commit = "a6de9a8b61077fa63ad5c3ecbe2bc12e0cb4b4b9"
loc = 734
stars = 54159

["meilisearch"]
full_name = "meilisearch/meilisearch"
url = "https://github.com/meilisearch/meilisearch"
commit = "b98e2cef8165d2f7fd4fd9c1607fa7d37589617a"
loc = 174171
stars = 53488

["awesome-rust"]
full_name = "rust-unofficial/awesome-rust"
url = "https://github.com/rust-unofficial/awesome-rust"
commit = "ac32108aced77134afecc8024dcea20b69c7ff09"
loc = 962
stars = 52941

["starship"]
full_name = "starship/starship"
url = "https://github.com/starship/starship"
commit = "f7d583821a01d2429cef1f243228aa04055f4760"
loc = 39994
stars = 51451

["vaultwarden"]
full_name = "dani-garcia/vaultwarden"
url = "https://github.com/dani-garcia/vaultwarden"
commit = "a2ad1dc7c3d28834749d4b14206838d795236c27"
loc = 26895
stars = 49482

["typst"]
full_name = "typst/typst"
url = "https://github.com/typst/typst"
commit = "721a7b18dd105e9255dc45f1af1510465e78bf02"
loc = 85804
stars = 46527

["codex"]
full_name = "openai/codex"
url = "https://github.com/openai/codex"
commit = "9823de3cc6039bb0bb6b95aac9b771612b728f31"
loc = 97039
stars = 45797

["fuels-rs"]
full_name = "FuelLabs/fuels-rs"
url = "https://github.com/FuelLabs/fuels-rs"
commit = "48f3c437394207ce8c37342ad2ce6bb6cc8076ba"
loc = 36481
stars = 43583

["ruff"]
full_name = "astral-sh/ruff"
url = "https://github.com/astral-sh/ruff"
commit = "b83ac5e2345fbf75cfd859f87735daa5d41ad04b"
loc = 374161
stars = 42807

["Pake"]
full_name = "tw93/Pake"
url = "https://github.com/tw93/Pake"
commit = "525816554f25e483a796aa611da9f1f8419d88e1"
loc = 537
stars = 42548

["bevy"]
full_name = "bevyengine/bevy"
url = "https://github.com/bevyengine/bevy"
commit = "dfb809cc1a58c425c5289062c2c0d77036695e52"
loc = 335681
stars = 42494

["helix"]
full_name = "helix-editor/helix"
url = "https://github.com/helix-editor/helix"
commit = "bfcbef10c513108c7b43317569416c2eefc4ed44"
loc = 77510
stars = 40143

["fd"]
full_name = "sharkdp/fd"
url = "https://github.com/sharkdp/fd"
commit = "8c9c6bec75aeb938eec5a538c00d2527f3af15f6"
loc = 6552
stars = 39910

["lapce"]
full_name = "lapce/lapce"
url = "https://github.com/lapce/lapce"
commit = "9cdbcf6bdf440bc6db7c3f39f76fcf0cab6262ea"
loc = 61480
stars = 37415

["nushell"]
full_name = "nushell/nushell"
url = "https://github.com/nushell/nushell"
commit = "dba8fee9c36a6c1222004854345d487495965473"
loc = 266439
stars = 36613

["polars"]
full_name = "pola-rs/polars"
url = "https://github.com/pola-rs/polars"
commit = "bfa1cf81ce14be2ef9f8d6718ce39fa18e3e5a73"
loc = 338649
stars = 35535

["hyperswitch"]
full_name = "juspay/hyperswitch"
url = "https://github.com/juspay/hyperswitch"
commit = "32dd9e10e3103a906cfef49c7baa117778ea02f3"
loc = 712201
stars = 35039

["swc"]
full_name = "swc-project/swc"
url = "https://github.com/swc-project/swc"
commit = "bebcc1cd53afbf0d9044fa5650df83d75d14d257"
loc = 603433
stars = 32779

["tabby"]
full_name = "TabbyML/tabby"
url = "https://github.com/TabbyML/tabby"
commit = "01f8bb72de75221ebaa18247a6a727f494421d05"
loc = 40864
stars = 32181

["comprehensive-rust"]
full_name = "google/comprehensive-rust"
url = "https://github.com/google/comprehensive-rust"
commit = "17a04070ed4dc896f60d008d2e61b4c247bb64bd"
loc = 4131
stars = 32108

["yew"]
full_name = "yewstack/yew"
url = "https://github.com/yewstack/yew"
commit = "85050f50fb4d211f5a96a814e175467ca87681b3"
loc = 40293
stars = 32030

["servo"]
full_name = "servo/servo"
url = "https://github.com/servo/servo"
commit = "523ae17165660645e7aec2eeaed66be3f3d24134"
loc = 314235
stars = 31647

["fish-shell"]
full_name = "fish-shell/fish-shell"
url = "https://github.com/fish-shell/fish-shell"
commit = "97acc12d620f6ccb5af2095e6632bf96b872d9ce"
loc = 77458
stars = 31097

["linera-protocol"]
full_name = "linera-io/linera-protocol"
url = "https://github.com/linera-io/linera-protocol"
commit = "8ca10f5a7285340e1557d0da6c0a076433379e6f"
loc = 130627
stars = 31086

["dioxus"]
full_name = "DioxusLabs/dioxus"
url = "https://github.com/DioxusLabs/dioxus"
commit = "6cfe64209a5fd5ba72335b328b35498f7bf95e19"
loc = 92012
stars = 30713

["sniffnet"]
full_name = "GyulyVGC/sniffnet"
url = "https://github.com/GyulyVGC/sniffnet"
commit = "b61f014f6c780913c7426945a11f382afb0e3f63"
loc = 21724
stars = 30710

["influxdb"]
full_name = "influxdata/influxdb"
url = "https://github.com/influxdata/influxdb"
commit = "1b671633cae56a54634a9dfc57b83cfe916c895e"
loc = 85586
stars = 30696

["firecracker"]
full_name = "firecracker-microvm/firecracker"
url = "https://github.com/firecracker-microvm/firecracker"
commit = "22e84fe5b8acba0c51cd928f0923a325c43a60e5"
loc = 78136
stars = 30641

["zoxide"]
full_name = "ajeetdsouza/zoxide"
url = "https://github.com/ajeetdsouza/zoxide"
commit = "194f8e31e43876c008a88c3b7c468351267f0f21"
loc = 1786
stars = 30292

["surrealdb"]
full_name = "surrealdb/surrealdb"
url = "https://github.com/surrealdb/surrealdb"
commit = "3cf782ee17dc3de954772057d3d695eb28d16717"
loc = 201026
stars = 30136

["tokio"]
full_name = "tokio-rs/tokio"
url = "https://github.com/tokio-rs/tokio"
commit = "3698a6f153c3b3484a5231901aae441e39327768"
loc = 87991
stars = 29732

["rust-course"]
full_name = "sunface/rust-course"
url = "https://github.com/sunface/rust-course"
commit = "23248753378ce922ab90b96fe37bd635dc373a34"
loc = 3004
stars = 28792

["turborepo"]
full_name = "vercel/turborepo"
url = "https://github.com/vercel/turborepo"
commit = "ae5d6ef99b0243e58c0ea40a9c892322c313360a"
loc = 90790
stars = 28786

["yazi"]
full_name = "sxyazi/yazi"
url = "https://github.com/sxyazi/yazi"
commit = "cd6881c9fe88dfe73d91980829fd371f5eeec242"
loc = 38849
stars = 28668

["just"]
full_name = "casey/just"
url = "https://github.com/casey/just"
commit = "b7e7c46495b34e9407982ffbbb25eb2808ec40b7"
loc = 36739
stars = 27956

["iced"]
full_name = "iced-rs/iced"
url = "https://github.com/iced-rs/iced"
commit = "0a34496c793fd87c235e764317351a0aacd4f6d1"
loc = 70969
stars = 27771

["delta"]
full_name = "dandavison/delta"
url = "https://github.com/dandavison/delta"
commit = "c22adcea90a5f3de2419a058fb92f1ced2a9fd10"
loc = 25516
stars = 27661

["egui"]
full_name = "emilk/egui"
url = "https://github.com/emilk/egui"
commit = "f6fe3bff180d8f93ebd4ccf7c29201cf2fb8894d"
loc = 77751
stars = 26684

["zellij"]
full_name = "zellij-org/zellij"
url = "https://github.com/zellij-org/zellij"
commit = "bfbc7cd2af8bd13c81b87eb36f363ee406738db6"
loc = 173692
stars = 26608

["czkawka"]
full_name = "qarmin/czkawka"
url = "https://github.com/qarmin/czkawka"
commit = "eba7d53b4ff9acfa7f58b91a35664b62339529aa"
loc = 28974
stars = 26436

["qdrant"]
full_name = "qdrant/qdrant"
url = "https://github.com/qdrant/qdrant"
commit = "48203e414e4e7f639a6d394fb6e4df695f808e51"
loc = 223740
stars = 26423

["hyperfine"]
full_name = "sharkdp/hyperfine"
url = "https://github.com/sharkdp/hyperfine"
commit = "16348dcf354f812321856f4f464d7bf6af99b00c"
loc = 5155
stars = 26296

["atuin"]
full_name = "atuinsh/atuin"
url = "https://github.com/atuinsh/atuin"
commit = "2fc262db80522b35aff87f34502abe073c78d52a"
loc = 20753
stars = 26099

["Rocket"]
full_name = "rwf2/Rocket"
url = "https://github.com/rwf2/Rocket"
commit = "504efef179622df82ba1dbd37f2e0d9ed2b7c9e4"
loc = 40295
stars = 25416

["pingora"]
full_name = "cloudflare/pingora"
url = "https://github.com/cloudflare/pingora"
commit = "71a5f5a0985aa37d83c107980d263d84c0d5c245"
loc = 43114
stars = 25190

["Rust"]
full_name = "TheAlgorithms/Rust"
url = "https://github.com/TheAlgorithms/Rust"
commit = "ed7a42e71f3d1a877876c38dfa1ec0ee9a69e83c"
loc = 31499
stars = 24772

["exa"]
full_name = "ogham/exa"
url = "https://github.com/ogham/exa"
commit = "3d1edbb47052cb416ef9478106c3907586da5150"
loc = 7470
stars = 24171

["anki"]
full_name = "ankitects/anki"
url = "https://github.com/ankitects/anki"
commit = "1f9d943c8d33020301d449af3070f95617faf734"
loc = 65154
stars = 23976

["actix-web"]
full_name = "actix/actix-web"
url = "https://github.com/actix/actix-web"
commit = "429ff82a4bdb6f4862c0dab2811fed392fcf7b65"
loc = 55226
stars = 23705

["chroma"]
full_name = "chroma-core/chroma"
url = "https://github.com/chroma-core/chroma"
commit = "01fae4c9d831ab4ab368e62d69b5254be0c2fd10"
loc = 131939
stars = 23688

["tools"]
full_name = "rome/tools"
url = "https://github.com/rome/tools"
commit = "392d188a49d70e495f13b1bb08cd7d9c43690f9b"
loc = 247459
stars = 23576

["axum"]
full_name = "tokio-rs/axum"
url = "https://github.com/tokio-rs/axum"
commit = "86e4442888b853490cf86cb351e02ad5bdf4a1fb"
loc = 29364
stars = 23307

["difftastic"]
full_name = "Wilfred/difftastic"
url = "https://github.com/Wilfred/difftastic"
commit = "65a803b203c61c96a4a0f14ab5db7d42bc1e5f7e"
loc = 18898
stars = 23173

["fnm"]
full_name = "Schniz/fnm"
url = "https://github.com/Schniz/fnm"
commit = "1ebc90decf58c2176dcbd4f8ac00ecb3adb1de12"
loc = 3743
stars = 22311

["tree-sitter"]
full_name = "tree-sitter/tree-sitter"
url = "https://github.com/tree-sitter/tree-sitter"
commit = "0cf6e7c5074e20781d8c4540bc71ab905843a24b"
loc = 44610
stars = 22217

["wezterm"]
full_name = "wezterm/wezterm"
url = "https://github.com/wezterm/wezterm"
commit = "bf9a2aeebacec19fd07b55234d626f006b22d369"
loc = 380707
stars = 22077

["fhevm"]
full_name = "zama-ai/fhevm"
url = "https://github.com/zama-ai/fhevm"
commit = "18898aa10463b126b1a1d3d932adf5b431ddbf81"
loc = 174066
stars = 22022

["Graphite"]
full_name = "GraphiteEditor/Graphite"
url = "https://github.com/GraphiteEditor/Graphite"
commit = "3cfacccc610348ad0bc438e50b5c2770a85608c8"
loc = 99712
stars = 21862

["coreutils"]
full_name = "uutils/coreutils"
url = "https://github.com/uutils/coreutils"
commit = "b4f8eac90c560ee8e263df5f92687f6437e9315c"
loc = 159081
stars = 21774

["biome"]
full_name = "biomejs/biome"
url = "https://github.com/biomejs/biome"
commit = "a8e73018a8c9e34a182624a91389e19d1fa7817f"
loc = 574477
stars = 21321

["sonic"]
full_name = "valeriansaliou/sonic"
url = "https://github.com/valeriansaliou/sonic"
commit = "722bfece335c8e9cc926684c85d92c52368f5b1f"
loc = 29112
stars = 20985

["jj"]
full_name = "jj-vcs/jj"
url = "https://github.com/jj-vcs/jj"
commit = "e541d384acf44ef3a1dd118ab95bf236bcba9c5f"
loc = 172394
stars = 20665

["gitui"]
full_name = "gitui-org/gitui"
url = "https://github.com/gitui-org/gitui"
commit = "1d2248571dbec63563ac360de46d6920209d96cd"
loc = 38901
stars = 20611

["RustPython"]
full_name = "RustPython/RustPython"
url = "https://github.com/RustPython/RustPython"
commit = "1aea1467da5269922feb6cdc099f2112b3ac90db"
loc = 119271
stars = 20573

["slint"]
full_name = "slint-ui/slint"
url = "https://github.com/slint-ui/slint"
commit = "a11a60741d39f8383a38d093bedd6f0ddb686a9a"
loc = 163332
stars = 20503

["gleam"]
full_name = "gleam-lang/gleam"
url = "https://github.com/gleam-lang/gleam"
commit = "195c44abaf4faca7edf2ca2bccfbce90c4be115f"
loc = 163795
stars = 20425

["vector"]
full_name = "vectordotdev/vector"
url = "https://github.com/vectordotdev/vector"
commit = "f054f9c1371be239eeac85fb79ab20d101cb71df"
loc = 269040
stars = 20425

["mdBook"]
full_name = "rust-lang/mdBook"
url = "https://github.com/rust-lang/mdBook"
commit = "4e41c844c305bc6f34b79bf5580b9169b1fc6364"
loc = 12915
stars = 20395

["wasmer"]
full_name = "wasmerio/wasmer"
url = "https://github.com/wasmerio/wasmer"
commit = "4edd8a9d0eddae3feda6e6cb40f0cc95c7452dc7"
loc = 239168
stars = 20099

["goose"]
full_name = "block/goose"
url = "https://github.com/block/goose"
commit = "b07b3bce1418547f0e025199fe936b0acc645342"
loc = 81262
stars = 20080

["neon"]
full_name = "neondatabase/neon"
url = "https://github.com/neondatabase/neon"
commit = "5e85c02f376d4714156bcd5b2d9e76e82f3e35ad"
loc = 231615
stars = 19845

["xi-editor"]
full_name = "xi-editor/xi-editor"
url = "https://github.com/xi-editor/xi-editor"
commit = "a2dea3059312795c77caadc639df49bf8a7008eb"
loc = 29225
stars = 19838

["mise"]
full_name = "jdx/mise"
url = "https://github.com/jdx/mise"
commit = "b2270e4f4e547651d171991ddb0274b49b1969bd"
loc = 54705
stars = 19711

["leptos"]
full_name = "leptos-rs/leptos"
url = "https://github.com/leptos-rs/leptos"
commit = "bbf5bf9170aa862053619f5c939fc885beaa7e99"
loc = 95175
stars = 19214

["Bend"]
full_name = "HigherOrderCO/Bend"
url = "https://github.com/HigherOrderCO/Bend"
commit = "d184863f03e796d1d657958a51dd6dd331ade92d"
loc = 14274
stars = 19025

["cube"]
full_name = "cube-js/cube"
url = "https://github.com/cube-js/cube"
commit = "ea477a5616282565f86e9df3278809b8a10049a9"
loc = 215996
stars = 18915

["relay"]
full_name = "facebook/relay"
url = "https://github.com/facebook/relay"
commit = "b2b07a6fabb9afc25d66ba743c4fe0a418048d78"
loc = 110718
stars = 18858

["spotify-tui"]
full_name = "Rigellute/spotify-tui"
url = "https://github.com/Rigellute/spotify-tui"
commit = "c4dcf6b9fd8318017acbdd7ec005955e26cf2794"
loc = 10828
stars = 18570

["candle"]
full_name = "huggingface/candle"
url = "https://github.com/huggingface/candle"
commit = "e677576e47d0126a5e85f2d3428b95fa06e3de90"
loc = 147091
stars = 18235

["RustScan"]
full_name = "bee-san/RustScan"
url = "https://github.com/bee-san/RustScan"
commit = "26000366215857d9521229afe103b28bd336374a"
loc = 2544
stars = 18133

["universal-android-debloater"]
full_name = "0x192/universal-android-debloater"
url = "https://github.com/0x192/universal-android-debloater"
commit = "11f27c671cba278d71296cdef4c5a5dba06add5e"
loc = 3829
stars = 17946

["hurl"]
full_name = "Orange-OpenSource/hurl"
url = "https://github.com/Orange-OpenSource/hurl"
commit = "982653e8d3669a5bc4a6708b4c1f5d5c73c38807"
loc = 52805
stars = 17819

["eza"]
full_name = "eza-community/eza"
url = "https://github.com/eza-community/eza"
commit = "05d20d11c488b2ad3f0d63ac0b529281cc1c16ef"
loc = 13196
stars = 17672

["SpacetimeDB"]
full_name = "clockworklabs/SpacetimeDB"
url = "https://github.com/clockworklabs/SpacetimeDB"
commit = "a16bfaa88b669cc634e69aa17560398a671f5892"
loc = 150658
stars = 17623

["ruffle"]
full_name = "ruffle-rs/ruffle"
url = "https://github.com/ruffle-rs/ruffle"
commit = "a388d0ecbbfd9ac93c4d8f91c78f41e69ded9e86"
loc = 187805
stars = 17259

["wasmtime"]
full_name = "bytecodealliance/wasmtime"
url = "https://github.com/bytecodealliance/wasmtime"
commit = "ea133c32a582ef7689f08f136d08ef65215225a8"
loc = 497818
stars = 16961
